DROP DATABASE IF EXISTS spotme_dev;
CREATE DATABASE spotme_dev;

DROP TABLE IF EXISTS emails;

CREATE TABLE emails (
  id SERIAL PRIMARY KEY,
  email VARCHAR(50) UNIQUE NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);